---
- name: Install essentials
  apt:
    name:
      - net-tools
      - ncdu
      - vnstat
      - tree
      - htop
      - zip
      - git
      - ufw
      - jq
      - bash-completion
      - cpufrequtils
      - ccze
      - nginx
    state: latest
    update_cache: true
